- name: Create user folder  in go_path
  file:
        dest="{{ go_path }}/src/github.com/allan-simon"
        state=directory
- name: link source folder into workspace
  file:
        src=/vagrant/src
        dest="{{ go_path }}/src/github.com/allan-simon/sentence-aligner"
        state=link

- name: Install go Packages required by the app
  command: >
      go get -u {{ item }}
  environment:
      GOPATH: "{{ go_path }}"
      GOROOT: "{{ go_root }}"
      PATH: "{{ go_root }}/bin:{{ go_path }}/bin:/usr/bin:/bin"
  with_items:
      - github.com/emicklei/go-restful
      - github.com/lib/pq 
