---
- name: PostgreSQL server and client
  apt: name=postgresql-9.3,libpq-dev,python-psycopg2,postgresql-contrib

- name: PostgreSQL database user
  sudo_user: postgres
  postgresql_user: name={{ DBUSER }} password={{ DBPASSWORD }}

- name: PostgreSQL database init
  sudo_user: postgres
  postgresql_db: name={{ DBNAME }} owner={{ DBUSER }}

- name: Activate uuid extension
  sudo_user: postgres
  postgresql_ext: name=uuid-ossp db={{ DBNAME }}
