---
- name: Symlink config files in rc folder
  file: src=/vagrant/provisioning/roles/vim/files/{{ item }} dest=/home/vagrant/{{ item }} state=link
  with_items:
    - .vimrc
    - .vim
- name: Create ~/src folder
  file: dest=/home/vagrant/src/vim-pathogen state=directory
- name: Check out pathogen
  git:
      repo=https://github.com/tpope/vim-pathogen.git
      dest=/home/vagrant/src/vim-pathogen
      update=yes
- name: Create /vagrant/provisioning/roles/vim/files/.vim/autoload folder
  file: dest=/vagrant/provisioning/roles/vim/files/.vim/autoload state=directory
- name: Symlink pathogen into ~/.vim/autoload
  file:
      src=/home/vagrant/src/vim-pathogen/autoload/pathogen.vim
      dest=/home/vagrant/.vim/autoload/pathogen.vim
      state=link


- name: Check out vim-go
  git:
    repo=https://github.com/fatih/vim-go.git
    dest=/home/vagrant/src/vim-go
    update=yes
- name: Ensure ~/.vim/bundle exists
  file:
    dest=/home/vagrant/.vim/bundle
    state=directory
- name: Symlink vim-go to .vim/bundle
  file:
    src=/home/vagrant/src/vim-go
    dest=/home/vagrant/.vim/bundle/vim-go
    state=link


- name: Install apt packages for YouCompleteMe vim completion engine
  sudo: yes
  apt:
    name={{ item }} state=latest
  with_items:
    - build-essential
    - cmake
    - python-dev
- name: Check out YouCompleteMe
  git:
    repo=https://github.com/Valloric/YouCompleteMe.git
    dest={{ home }}/src/YouCompleteMe
- name: Symlink YouCompleteMe to ~/vim/bundle
  file:
    src={{ home }}/src/YouCompleteMe
    dest={{ home }}/.vim/bundle/YouCompleteMe
    state=link
- name: Compile YouCompleteMe binaries
  command: ./install.sh --clang-completer
    chdir={{ home }}/src/YouCompleteMe
    creates={{ home }}/src/YouCompleteMe/third_party/ycmd/ycm_core.so
